import { useState } from 'react'
import api from '../../lib/api'

export default function Partner() {
  const [code, setCode] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [data, setData] = useState(null)

  const fetchSummary = async (e) => {
    e.preventDefault()
    if (!code) return
    setLoading(true)
    setError('')
    setData(null)
    try {
      const { data } = await api.get(`/api/partners/summary/${code}`)
      setData(data)
    } catch (e) {
      setError('Could not find details for this coupon. Please check the code.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 py-10 px-4">
      <div className="max-w-5xl mx-auto space-y-6">
        <header className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
          <div>
            <h1 className="text-2xl font-semibold">Partner Dashboard</h1>
            <p className="text-sm text-gray-600">
              Enter your coupon code to see total transaction amount generated by your referrals and your commission.
              Product details are hidden; only totals are shown.
            </p>
          </div>
          <form onSubmit={fetchSummary} className="flex flex-col sm:flex-row gap-3">
            <input
              className="border p-2 rounded-md bg-white shadow-sm min-w-[220px]"
              placeholder="Your coupon code"
              value={code}
              onChange={e=>setCode(e.target.value)}
            />
            <button
              type="submit"
              className="px-4 py-2 bg-blue-600 text-white rounded-md shadow-sm disabled:opacity-50"
              disabled={!code || loading}
            >
              {loading ? 'Loading...' : 'View'}
            </button>
          </form>
        </header>

        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 text-sm px-4 py-2 rounded-md">
            {error}
          </div>
        )}

        {data && (
          <div className="space-y-6">
            <section className="bg-white border rounded-xl shadow-sm p-4 md:p-6">
              <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4 border-b pb-4 mb-4">
                <div>
                  <div className="text-xs font-medium text-gray-500 uppercase tracking-wide">Partner</div>
                  <div className="text-lg font-semibold">{data.partnerName || '-'}</div>
                  {data.partnerPhone && <div className="text-xs text-gray-600">{data.partnerPhone}</div>}
                  {data.partnerEmail && <div className="text-xs text-gray-600">{data.partnerEmail}</div>}
                </div>
                <div className="text-right">
                  <div className="text-xs font-medium text-gray-500 uppercase tracking-wide">Coupon</div>
                  <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-blue-50 text-blue-700 text-sm font-semibold">
                    <span>{data.code}</span>
                  </div>
                  <div className="text-xs text-gray-600 mt-1">Commission rate: {data.commissionPercent}%</div>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-3">
                <div className="bg-gray-50 border rounded-lg p-3">
                  <div className="text-xs text-gray-500 uppercase tracking-wide">Total transactions</div>
                  <div className="mt-1 text-xl font-semibold">₹{data.totalSales.toFixed(2)}</div>
                </div>
                <div className="bg-gray-50 border rounded-lg p-3">
                  <div className="text-xs text-gray-500 uppercase tracking-wide">Total commission</div>
                  <div className="mt-1 text-xl font-semibold">₹{data.totalCommission.toFixed(2)}</div>
                </div>
                <div className="bg-gray-50 border rounded-lg p-3">
                  <div className="text-xs text-gray-500 uppercase tracking-wide">Paid to you</div>
                  <div className="mt-1 text-xl font-semibold text-green-700">₹{data.totalPaid.toFixed(2)}</div>
                </div>
                <div className="bg-gray-50 border rounded-lg p-3">
                  <div className="text-xs text-gray-500 uppercase tracking-wide">Pending</div>
                  <div className="mt-1 text-xl font-semibold text-orange-700">₹{data.balance.toFixed(2)}</div>
                </div>
              </div>
            </section>

            {data.payouts && data.payouts.length>0 && (
              <section className="bg-white border rounded-xl shadow-sm p-4 md:p-6">
                <div className="flex items-center justify-between mb-3">
                  <h2 className="text-sm font-semibold">Payout history</h2>
                  <span className="text-xs text-gray-500">{data.payouts.length} payout{data.payouts.length>1?'s':''}</span>
                </div>
                <div className="max-h-64 overflow-y-auto divide-y text-xs text-gray-700">
                  {data.payouts.map((p, idx)=>(
                    <div key={idx} className="py-2 flex flex-col sm:flex-row sm:justify-between gap-2">
                      <div>
                        <div className="font-medium">₹{p.amount.toFixed(2)} • {p.method}</div>
                        {p.utr && <div>UTR: {p.utr}</div>}
                        {p.razorpayPaymentId && <div>Razorpay: {p.razorpayPaymentId}</div>}
                        {p.notes && <div>Note: {p.notes}</div>}
                      </div>
                      <div className="text-gray-500 text-right">{new Date(p.createdAt).toLocaleString()}</div>
                    </div>
                  ))}
                </div>
              </section>
            )}
          </div>
        )}

        {!data && !loading && !error && (
          <div className="text-center text-sm text-gray-500">
            Enter your coupon code above to view your dashboard.
          </div>
        )}
      </div>
    </div>
  )
}

