import { useState } from 'react'
import api from '../../lib/api'

export default function Partner() {
  const [code, setCode] = useState('')
  const [loading, setLoading] = useState(false)
  const [error, setError] = useState('')
  const [data, setData] = useState(null)

  const fetchSummary = async (e) => {
    e.preventDefault()
    if (!code) return
    setLoading(true)
    setError('')
    setData(null)
    try {
      const { data } = await api.get(`/api/partners/summary/${code}`)
      setData(data)
    } catch (e) {
      setError('Could not find details for this coupon. Please check the code.')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div className="min-h-screen bg-gray-50 py-12 px-4">
      <div className="max-w-5xl mx-auto space-y-8">
        <header className="flex flex-col md:flex-row md:items-center md:justify-between gap-6">
          <div className="max-w-2xl">
            <h1 className="text-3xl font-bold text-gray-900">Partner Dashboard</h1>
            <p className="mt-2 text-base text-gray-600 leading-relaxed">
              Enter your coupon code to see total transaction amount generated by your referrals and your commission.
              Product details are hidden; only totals are shown.
            </p>
          </div>
          <form onSubmit={fetchSummary} className="flex flex-col sm:flex-row gap-3">
            <input
              className="border p-3 rounded-lg bg-white shadow-sm min-w-[240px] text-base"
              placeholder="Your coupon code"
              value={code}
              onChange={e=>setCode(e.target.value)}
            />
            <button
              type="submit"
              className="px-6 py-3 bg-blue-600 text-white rounded-lg shadow-md font-semibold hover:bg-blue-700 transition-colors disabled:opacity-50"
              disabled={!code || loading}
            >
              {loading ? 'Loading...' : 'View Details'}
            </button>
          </form>
        </header>

        {error && (
          <div className="bg-red-50 border border-red-200 text-red-700 text-base px-5 py-3 rounded-lg">
            {error}
          </div>
        )}

        {data && (
          <div className="space-y-8">
            <section className="bg-white border rounded-2xl shadow-sm p-6 md:p-10">
              <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-6 border-b pb-8 mb-8">
                <div>
                  <div className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-1">Partner</div>
                  <div className="text-2xl font-bold text-gray-900">{data.partnerName || '-'}</div>
                  <div className="mt-2 space-y-1">
                    {data.partnerPhone && <div className="text-sm text-gray-600 font-medium flex items-center gap-2"><span className="w-1 h-1 rounded-full bg-gray-400" />{data.partnerPhone}</div>}
                    {data.partnerEmail && <div className="text-sm text-gray-600 font-medium flex items-center gap-2"><span className="w-1 h-1 rounded-full bg-gray-400" />{data.partnerEmail}</div>}
                  </div>
                </div>
                <div className="md:text-right">
                  <div className="text-sm font-bold text-gray-400 uppercase tracking-widest mb-2">Coupon Code</div>
                  <div className="inline-flex items-center gap-3 px-4 py-2 rounded-xl bg-blue-50 text-blue-700 text-lg font-bold">
                    <span>{data.code}</span>
                  </div>
                  <div className="text-sm text-gray-600 font-semibold mt-3 bg-gray-50 inline-block px-3 py-1 rounded-md">Commission rate: {data.commissionPercent}%</div>
                </div>
              </div>

              <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
                <div className="bg-gray-50 border rounded-xl p-5">
                  <div className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">Total Sales</div>
                  <div className="text-2xl font-bold text-gray-900">₹{data.totalSales.toLocaleString()}</div>
                </div>
                <div className="bg-gray-50 border rounded-xl p-5">
                  <div className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">Commission Earned</div>
                  <div className="text-2xl font-bold text-blue-600">₹{data.totalCommission.toLocaleString()}</div>
                </div>
                <div className="bg-gray-50 border rounded-xl p-5">
                  <div className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">Amount Paid</div>
                  <div className="text-2xl font-bold text-green-600">₹{data.totalPaid.toLocaleString()}</div>
                </div>
                <div className="bg-gray-50 border rounded-xl p-5">
                  <div className="text-xs font-bold text-gray-500 uppercase tracking-wider mb-2">Pending Balance</div>
                  <div className="text-2xl font-bold text-orange-600">₹{data.balance.toLocaleString()}</div>
                </div>
              </div>
            </section>

            {data.payouts && data.payouts.length>0 && (
              <section className="bg-white border rounded-xl shadow-sm p-4 md:p-6">
                <div className="flex items-center justify-between mb-3">
                  <h2 className="text-sm font-semibold">Payout history</h2>
                  <span className="text-xs text-gray-500">{data.payouts.length} payout{data.payouts.length>1?'s':''}</span>
                </div>
                <div className="max-h-64 overflow-y-auto divide-y text-xs text-gray-700">
                  {data.payouts.map((p, idx)=>(
                    <div key={idx} className="py-2 flex flex-col sm:flex-row sm:justify-between gap-2">
                      <div>
                        <div className="font-medium">₹{p.amount.toFixed(2)} • {p.method}</div>
                        {p.utr && <div>UTR: {p.utr}</div>}
                        {p.razorpayPaymentId && <div>Razorpay: {p.razorpayPaymentId}</div>}
                        {p.notes && <div>Note: {p.notes}</div>}
                      </div>
                      <div className="text-gray-500 text-right">{new Date(p.createdAt).toLocaleString()}</div>
                    </div>
                  ))}
                </div>
              </section>
            )}
          </div>
        )}

        {!data && !loading && !error && (
          <div className="text-center text-sm text-gray-500">
            Enter your coupon code above to view your dashboard.
          </div>
        )}
      </div>
    </div>
  )
}

